[package]
name = "payments_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
rust_decimal = "1.37.2"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
tempfile = "3.20.0"
